// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtOEAnvnnVIM5uFS8rCx5G3Cm0qvc0zKA',
    appId: '1:1058793240603:web:44041e321ec668bbce60be',
    messagingSenderId: '1058793240603',
    projectId: 'sns-project-2e3e4',
    authDomain: 'sns-project-2e3e4.firebaseapp.com',
    storageBucket: 'sns-project-2e3e4.appspot.com',
    measurementId: 'G-14DKNPVVJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvYM2JzaU19J6aOHV-2x3fxRQg280MTU',
    appId: '1:1058793240603:android:59dd0ddb874c28b4ce60be',
    messagingSenderId: '1058793240603',
    projectId: 'sns-project-2e3e4',
    storageBucket: 'sns-project-2e3e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV13k2Anwxg1DQkTUWiEuotmIn77KwkJU',
    appId: '1:1058793240603:ios:8b8bda6485167e09ce60be',
    messagingSenderId: '1058793240603',
    projectId: 'sns-project-2e3e4',
    storageBucket: 'sns-project-2e3e4.appspot.com',
    androidClientId: '1058793240603-jeusinppab49lcinbhk5h476isu9fgd3.apps.googleusercontent.com',
    iosClientId: '1058793240603-9tv3hkd6ge6enif317lijilsdajte31h.apps.googleusercontent.com',
    iosBundleId: 'com.example.prodect1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV13k2Anwxg1DQkTUWiEuotmIn77KwkJU',
    appId: '1:1058793240603:ios:8b8bda6485167e09ce60be',
    messagingSenderId: '1058793240603',
    projectId: 'sns-project-2e3e4',
    storageBucket: 'sns-project-2e3e4.appspot.com',
    androidClientId: '1058793240603-jeusinppab49lcinbhk5h476isu9fgd3.apps.googleusercontent.com',
    iosClientId: '1058793240603-9tv3hkd6ge6enif317lijilsdajte31h.apps.googleusercontent.com',
    iosBundleId: 'com.example.prodect1',
  );
}
