name: Android Release

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.9"
          channel: 'stable'
          
      - name: Import Flutter Package
        run: |
          cd prodect1
          flutter pub get
          
      - name: Flutter build
        run: flutter build
          
#       - name: Ensure the Dart code is formatted correctly
#         run: flutter format --set-exit-if-changed --dry-run .
        
#       - name: Test
#         run: flutter test          
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge dev branch into main
        run: |
          git merge --no-ff --allow-unrelated-histories origin/dev
          git push origin main
