name: Android Release

on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.9"
          channel: 'stable'
          
      - name: Import Flutter Package
        run: |
          cd prodect1
          flutter pub get
          
      - name: Flutter build
        run: flutter build
        
      - name: Merge dev branch into main
        run: |
          git fetch origin 
          git checkout dev
          git checkout main
          git merge main
                
