name: Android Release

on:
  push:
    branches: 
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.9"
          channel: 'stable'

      - name: Import Flutter Package
        run: |
          cd prodect1
          flutter pub get

      - name: Flutter build
        run: flutter build

      - name: Merge test branch into main
        run: |
          git fetch origin
          git checkout main
          git merge dev --allow-unrelated-histories

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

