name: Android Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.9"
          channel: 'stable'
          
      - name: Install packages
        run: flutter pub get
        
      - name: Linter
        run: flutter analyze
        
      - name: Test
        run: flutter test
        
