name: Android Release

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
         
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.9"
          channel: 'stable'
          
      - name: Import Flutter Package
        run: |
          cd prodect1
          flutter pub get
          
#       - name: Ensure the Dart code is formatted correctly
#         run: flutter format --set-exit-if-changed --dry-run .
        
#       - name: Test
#         run: flutter test
        
      - name: Merge
        run: |
          git checkout main
          git merge dev
        
